### ISSUE TITLE
Voice tasks automation additional text blocks

### ISSUE THREAD

**Issue by davros123** [TomFrankly/pipedream-notion-voice-tasks#13]
https://thomasjfrank.com/notion-chatgpt-voice-tasks

Love the automation - however it is adding additional blocks that show in my task board
This is causing clutter on my task kanban board.

**How do I remove this additional text from the automation**
(ie. 
`🤖 This task was created via the following source: Pipedream. The cost of this request was $0.0031.
**Full text of task:**
Improve my automations by tomorrow.
**Entire request sent to ChatGPT:**
Improve my automations by tomorrow`

![image](https://github.com/TomFrankly/pipedream-notion-voice-tasks/assets/2758224/12c77a42-f957-4849-8818-5cc7544f1795)

**Comment by TomFrankly** [comment]
@davros123 for now, you won't be able to remove that text unless you'd like to fork the project and publish it as your own Pipedream CLI component: https://pipedream.com/docs/cli/install/

I currently don't have dev time in my schedule to make updates to this workflow, but it's also important for that text to be somewhere in the task page. This is because you might end up recording details of a task that ChatGPT gets wrong or skips in rare occasions, so having the full text of what you said is an important fallback.

When I get more dev time in the future, I can look into creating an option to put this info in a text property instead of the page body. You'll also be able to use a better version of this workflow in our upcoming app, Flylighter: https://flylighter.com/

**Comment by davros123** [comment]
@TomFrankly  Thanks for the reply and a HUGE thankyou 🙇  for having the code available !
I will have a go at changing it - it will be a great learning experience for me :) 

THANKYOU !

**Comment by davros123** [comment]
@TomFrankly   I am having difficulty building this - I know you do not provide support bu tif you get a moment would appreciate some steps on what to do to build this repo either here or in the [pipedream slack ](https://pipedream-users.slack.com/archives/CPTJYRY5A/p1702451822190229?thread_ts=1702365973.619559&cid=CPTJYRY5A)

ran `npm run build`  and it builds for other items , but not this component (located in F:/pd/pipedream-master/components/personal/voice_tasks) 
ie..
```
F:\pd\pipedream-master>npm run build

> pipedream@1.2.1 build
> npx tsc --build | node scripts/tsPostBuild.mjs

F:/pd/pipedream-master/components/tookan/dist/common/requestParams.mjs
F:/pd/pipedream-master/components/tookan/dist/common/responseSchemas.mjs
etc etc
```

**Comment by TomFrankly** [comment]
@davros123 unfortunately I really can't provide support on CLI stuff right now, but one thing I'll mention is that I don't recall ever doing `npm run build` when deploying CLI compoents.

I just do `pd publish Notion-Voice-Notes.mjs` in my VS Code terminal, and it zips up all my files and publishes them as an internal action I can use in my account. Aside from that, I do your normal `git add .`, `git commit -m "message"` and `git push origin main` here for this repo (which doesn't use Pipedream's Github sync, btw).

If you need help on CLI components, I'd recommend asking Pipedream staff in the Slack or Discourse communities!

**Comment by davros123** [comment]
@TomFrankly Thanks. Turns out the npm run was not needed and is not the issue.

For completeness, the reason I could not publish was the file size. There is a limit in Notion of 64k and this code is 85k. 
It needs to be minified before being published then it will be published with no errors. This brings the size down to 55k

I installed terser for this..

`npm install terser -g
terser note.js -o note-mini.js -c -m`

Then publish the mini version.
`pd publish note-mini.js`
