### ISSUE TITLE
Issue with Automation - Notion Voice Tasks

### ISSUE THREAD

**Issue by Active101x** [TomFrankly/pipedream-notion-voice-tasks#5]
Issue for Android automation.

There is an issue when selecting my Tasks Database. It doees seem to find my Takss db, which is called All Tasks AA. But thee name of my db in the list shows this instead: All Tasks AA -- (used for Ultimate Tasks). Thats not how my db is actually called. Not sure if thats the issue, but in any case, I have selected it anyway and it seems that it is indeed my db because the name of the properties match my db (ex: my assignee property is called "Who" which is how its showing in the Pipe dream Assignee options field.

So I then select the correct properties for : Task name, Due Date, Assignee, Project, Status.

At this point, I should be able to click Configue Test right? But it not clickable (stays grey). The "Priority (REQUIRED for Ultimate Brain/Ultimate Tasks)" field is highlited in blue as soon as i select an otion in the "Task Name (Required)" field.

I think the automation thinks im using Ultimate tasks. I dont understand why, I even changed the name of my Tasks db (oviously when i make a change i reset the whole pipedream processs, generate a new link, add it to Tasker, and then regenerate a post request, etc..)

So aftter havbing sselected all the correct proterties, I can't do anything from here because I have to select an option in the blue highletted field "Priority (REQUIRED for Ultimate Brain/Ultimate Tasks)".

I have troushooted in multiple ways. Going at it for about 3 hours. 

If I go ahead and ssselectt an option in the "Priority (REQUIRED for Ultimate" field, there are 3 options: (Priority, Frequency, and Status), which are indeed fields from my db. If I select the Frequency priority, it lets me make a test, butt fails. Here is the error:

Error
Error: Missing property "task" in request body.

DETAILS
    at Object.createFallbackTask (file:///tmp/__pdg__/dist/code/401fd95cd39e6108f703556edf7d23d3b97e055c0d913a006cd9655a7250311f/component.mjs:1:52004)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Object.checkBody (file:///tmp/__pdg__/dist/code/401fd95cd39e6108f703556edf7d23d3b97e055c0d913a006cd9655a7250311f/component.mjs:1:47636)
    at Object.run (file:///tmp/__pdg__/dist/code/401fd95cd39e6108f703556edf7d23d3b97e055c0d913a006cd9655a7250311f/component.mjs:1:52231)
    at null.executeComponent (/var/task/launch_worker.js:229:22)
    at MessagePort.messageHandler (/var/task/launch_worker.js:726:28)

Exports:

steps.Parse_and_Create_Tasks
{1}
$response
{3}
status:
200
headers
{0}
body:
Task(s) has been sent to ChatGPT for processing.

------------

If I choose Priority or Status, it doesnt let me make a testt until I fill out the next fields. I tried every option for troubleshooting and didnt work. It does let me test the automattion, which give me the same error as above.

**Comment by TomFrankly** [comment]
Hello!

The error `Error: Missing property "task" in request body.` actually indicates an earlier issue: Your Android device sent a request to the workflow, but it's missing the `task` property.

If you look at the `body` part of the Exports area in the trigger, you should see these four keys:

![CleanShot 2023-09-08 at 16 37 02@2x](https://github.com/TomFrankly/pipedream-notion-voice-tasks/assets/684961/7ddc5628-94d6-4c59-97cd-ba2499cf2a61)

If you don't see them, could you share a screenshot of what you do see there?

Also, please let me know if you have imported the Tasker workflow that I shared, or if you're trying to use a Tasker workflow you've built yourself.

In the Android setup video, you can see that the Javascriptlet is set up to send those four properties in the request:

![CleanShot 2023-09-08 at 16 39 53@2x](https://github.com/TomFrankly/pipedream-notion-voice-tasks/assets/684961/3daffd78-62f4-4c5c-b790-15abe74ed018)

And in this part of the video, you'll see me make a request that contains those properties in the Exports tab: https://youtu.be/hTpQQwzvlbc?si=syDn6MD5Iudu8htS&t=342

So if that's not happening for you, we'll need to figure out why that might be. Please let me know if your Android device showed any dialogue messages or warnings that weren't shown in this video. I bought an Android phone specifically to build and test this workflow for Android users, but there's no way I can test on every possible device out there.

Also, the "(Used for Ultimate Tasks)" part is just some code that I added into the script in order to help users find the correct database more easily. It is auto-appeneded onto any database that includes "All Tasks" in the name.

**Comment by Active101x** [comment]
Thanks, i fixed tthe problem. Im using your Tasker Automation. But i wasnt receiving the 4 elementss you showed in thee Export -> Body. So I retested everything until i got the elements and its now working. Thanks! 

PS: Do you have an automation for Whatss app meessages (voicee or/and audio) to end up in Notion?

**Comment by TomFrankly** [comment]
@Active101x what did you have to do to fix the Tasker automation? You're not the only one who's had this issue, so I'd love to write a FAQ section for it – or ideally figure out why it's happening.

I don't have anything for WhatsApp right now!

**Comment by Active101x** [comment]
I'm not sure what fixed it exactly, but It had to do with the generate post request and clicking the automation which I added on my phone home screen (the tasker automation).

I think that previously, I generated the post request before having finished filling out the pipe dream fields (selecting the notion dB and properties).

I think that once everything is ready, I had to retry click ING on the automation (on my phone) and then selecting that new post request in pipedream, then testing the automation again (in pipedream).

Hope this helps!

**Comment by TomFrankly** [comment]
Ah, so you're saying that the first time you tested the Pipedream automation, you generated the Test Event using that "Generate Test Event" button instead of actually sending a test event from your phone?

That's helpful context! I'll make sure to cover that in the tutorial.

**Comment by TomFrankly** [comment]
Closing: Marked as a to-do in #6

**Comment by Active101x** [comment]
I did both the first time, but I guess I had to do it also after having filled out the rest of the fields in pipe dream.. Not too sure because I tried so many different things.
